from __future__ import annotations

import json
import re

from evidensia.models import Citation, ResearchState


def export_research(state: ResearchState, format_name: str) -> tuple[str, str, str]:
    format_name = format_name.lower()
    stem = re.sub(r"[^a-z0-9]+", "-", state.question.lower()).strip("-")[:70] or state.run_id
    if format_name == "json":
        return json.dumps(state.model_dump(mode="json"), ensure_ascii=False, indent=2), "application/json", f"{stem}.json"
    if format_name == "bibtex":
        return _bibtex(state), "application/x-bibtex", f"{stem}.bib"
    if format_name == "ris":
        return _ris(state), "application/x-research-info-systems", f"{stem}.ris"
    return _markdown(state), "text/markdown; charset=utf-8", f"{stem}.md"


def _markdown(state: ResearchState) -> str:
    report = state.final_report
    if not report:
        return f"# {state.question}\n\nResearch status: {state.status}\n"
    lines = [
        f"# {report.research_question}",
        "",
        f"**Confidence:** {report.confidence_score:.0%}",
        "",
        "## Executive summary",
        report.executive_summary,
        "",
        "## Conclusion",
        report.conclusion,
        "",
        "## Key findings",
        *[f"- {finding}" for finding in report.key_findings],
        "",
        "## Claims",
        *[f"- **{claim.status.title()} ({claim.confidence:.0%})** — {claim.statement}" for claim in report.claims],
        "",
        "## Limitations",
        *[f"- {item}" for item in report.limitations],
        "",
        "## Unresolved questions",
        *[f"- {item}" for item in report.unresolved_questions],
        "",
        "## Sources",
        *[f"{index}. {_citation_text(source)}" for index, source in enumerate(report.sources, start=1)],
        "",
        f"_Generated by Evidensia run `{state.run_id}` using {state.provider_manifest}._",
    ]
    return "\n".join(lines)


def _citation_text(citation: Citation) -> str:
    locator = f", p. {citation.page}" if citation.page else f", {citation.section}"
    link = f" — {citation.source_uri}" if citation.source_uri else ""
    return f"{citation.title}{locator}{link}"


def _bibtex(state: ResearchState) -> str:
    sources = state.final_report.sources if state.final_report else []
    entries = []
    for index, source in enumerate(sources, start=1):
        key = re.sub(r"[^a-z0-9]", "", source.title.lower())[:24] or f"source{index}"
        entries.append(
            "@misc{" + key + ",\n"
            f"  title = {{{source.title}}},\n"
            f"  url = {{{source.source_uri or ''}}},\n"
            f"  note = {{{source.section}{f', page {source.page}' if source.page else ''}}}\n"
            "}"
        )
    return "\n\n".join(entries) + ("\n" if entries else "")


def _ris(state: ResearchState) -> str:
    sources = state.final_report.sources if state.final_report else []
    blocks = []
    for source in sources:
        blocks.append("\n".join([
            "TY  - GEN",
            f"TI  - {source.title}",
            f"UR  - {source.source_uri or ''}",
            f"N1  - {source.section}{f', page {source.page}' if source.page else ''}",
            "ER  -",
        ]))
    return "\n\n".join(blocks) + ("\n" if blocks else "")
